version: "3"

services:
  node:
    # コンテナ名
    container_name: next_v2
    # build
    image: node:17-alpine3.12
    # コンテナの中に入る
    tty: true
    # ボリューム
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/.next
    # 環境変数
    environment:
      TZ: "Asia/Tokyo"
